version: "3.7"
services:

  pomodoro_tracker:
    container_name: pomodoro_tracker
    build: .
    depends_on:
      - db
    expose:
      - "8891"
    ports:
      - "8891:8891"
    networks:
      - backend

  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: pomodoro-tracker
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

networks:
  backend:
volumes:
  postgres: