version: "3.7"
services:

  pomodoro-tracker:
    container_name: pomodoro_tracker
    build: .
    depends_on:
      - pg_pomodoro
    ports:
      - "8891:8891"
    networks:
      - backend

  pg_pomodoro:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: pomodoro-tracker
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

networks:
  backend:
volumes:
  postgres: